language: generic
sudo: required
services:
  - docker

before-install:
  - docker build  -f Dockerfile.dev -t ahothman/docker-react .

script:
  - docker run -e CI=true ahothman/docker-react npm run test -- --coverage