language: node_js
node_js:
  - 8

sudo: required

services:
  - docker

before-install:
  - docker build  -f Dockerfile.dev -t ahothman/docker-react .

script:
  - bundle exec rake test
  - docker run -e CI=true ahothman/docker-react npm run test -- --coverage